name: fuelWise
description: A simple Dart server for calculating fuel requirements.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  json_annotation: ^4.0.1